[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm run build --filter=server..."]

[start]
cmd = "bun run dist/index.mjs"